EMOTION_LABELS = [
    "happy",
    "sad",
    "angry",
    "frustrated",
    "surprised",
    "fearful",
    "disgusted",
    "neutral",
]


GOEMOTIONS_LABELS = [
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise",
    "neutral",
]


GOEMOTIONS_MAPPING_NOTES = {
    "happy": [
        "joy",
        "amusement",
        "approval",
        "gratitude",
        "optimism",
        "love",
        "caring",
        "desire",
        "excitement",
        "pride",
        "relief",
    ],
    "sad": ["sadness", "grief", "disappointment", "remorse"],
    "angry": ["anger", "annoyance"],
    "frustrated": ["disapproval", "embarrassment", "confusion"],
    "surprised": ["surprise", "realization", "curiosity"],
    "fearful": ["fear", "nervousness"],
    "disgusted": ["disgust"],
    "neutral": ["neutral"],
}
